### ISSUE TITLE
Make a Windows package

### ISSUE THREAD

**Issue by BZ1G** [katherinelitor/GAEuploader#2]
The upstream Google Cloud SDK package for Windows is different from the ones for Mac and Linux. Instead of a tar.gz file, it is a [self-installing .exe](https://cloud.google.com/sdk/docs/quickstart-windows), GoogleCloudSDKInstaller.exe. The installer file is only 800 KB (compared to 9 MB for the Mac and Linux distributions), so it probably doesn't even include all the necessary files and only downloads them at install time.

One possibility is to simply distribute GoogleCloudSDKInstaller.exe, and instruct users to first run the installer before running the uploader.

We will also need a way to make the uploader double-clickable, because Windows doesn't have a Python interpreter by default.

**Comment by katherinelitor** [comment]
The new release, v1.2-beta, supports Windows platform.
