### ISSUE TITLE
Python 3.x compatibility

### ISSUE THREAD

**Issue by james-see** [katherinelitor/GAEuploader#4]
I dont understand why this wasnt written in Python 3 unless there was some requirement by google. I can try to help by forking and doing a pull request but havent looked at the codebase yet at all.

**Comment by katherinelitor** [comment]
You raised a good point. I used python 2 because Google Cloud SDK uses Python 2.7. If you can make a version that is compatible with both Python 2 and Python 3, that would be very appreciated!
